apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: devops-todo
spec:
  selector:
    app: todo-api
  ports:
    - port: 80
      targetPort: 8088
      nodePort: 30080
  type: NodePort